table Vendas
	lineageTag: 6dca8fcd-f5e0-4d2f-acf2-8b719577778e

	column Numero
		dataType: int64
		formatString: 0
		lineageTag: f02901a5-e7af-4dbb-a0f4-7199f31f9096
		summarizeBy: none
		sourceColumn: Numero

		annotation SummarizationSetBy = Automatic

	column 'Codigo do produto'
		dataType: int64
		formatString: 0
		lineageTag: b695367f-e0df-4011-bae7-f3aef186b77d
		summarizeBy: none
		sourceColumn: Codigo do produto

		annotation SummarizationSetBy = Automatic

	column Quantidade
		dataType: int64
		formatString: 0
		lineageTag: 1dcdca4d-00fa-4fd2-92f9-39c9f27071e3
		summarizeBy: sum
		sourceColumn: Quantidade

		annotation SummarizationSetBy = Automatic

	column 'Preco Calculado' = ```
			RELATED(Produtos[Preco])
			
			
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: a1d1c462-1eeb-4b6b-94b1-30ca26700c2e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Custo Calculado' = ```
			RELATED(Produtos[Custo]) 
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 64ae6671-a7d2-481d-84bd-7d84e9c50be9
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition Vendas = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents(#"Fonte Dados" & "dataset-vendas-livraria.xlsx"), null, true),
				    Table_1_Table = Fonte{[Item="Table_1",Kind="Table"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Table_1_Table,{{"Numero", Int64.Type}, {"Codigo do produto", Int64.Type}, {"Quantidade", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

